### ISSUE TITLE
...

### ISSUE THREAD

**Issue by complexpotato** [antony-jr/ama#1]
![doublechinfreak](https://user-images.githubusercontent.com/33967054/35833719-4e5013be-0aa0-11e8-8cdf-da853aa2bd19.JPG)

Looks like you never knew about that github sends me an email when commented...
At least next time just imagine, not commenting and deleting. All other people would have saw that too by now.

**Comment by antony-jr** [comment]
> Looks like you never knew about that github sends me an email when commented...

@Juniorn1003 I know exactly how a Mailing list works.... Infact Before even github , git used this feature. 

And Please see that **Only you get the email**. , I made sure that **no one sees that** ( Atleast those who did not enable email notification on all participating threads ). I really don't want to discourage you. But its really annoying when people do or say stuff they don't really know. In my view **Pulse and HyperPulse** is also considered to have a bad code base. **So Keep doing your Job and Sorry for that email.** 😢 😭 

In the very start I really did write horrible code like that , **So Keep Trying Hard and I apologize for that email**.
By the way How old are you ?

**Comment by antony-jr** [comment]
Next time you do anything please follow these guidlines,

📝 Use a succinct title and description.
😊 Be nice, civil and polite.
😍 If you include at least one emoji in your question, the feedback will probably come faster.

Next Time then... 👍
