### ISSUE TITLE
Custom Worldlist

### ISSUE THREAD

**Issue by Teokyun** [antony-jr/ama#11]
How do i add a custom worldlist on your passwordlist? Because i can provide specific passlist on my target.

**Comment by antony-jr** [comment]
@Teokyun This is command line basics , just mention the path to any text file with a list of passwords... Like this ``` $ instagram-py -u target_username -pl /your/path/to/your/custompasswordlist ```

**Comment by antony-jr** [comment]
@Teokyun I think you are pretty new to this but work hard to get a grasp! If you ever need help , open a issue at the official repo (https://github.com/antony-jr/instagram-py) , Do check the new **Instagram-Py Portable** which available at the **official repo**.  ( Portable version does not need to setup anything , even python and tor , just download and start using it!)

Thank You for your time!

**Comment by Teokyun** [comment]
Please make a video on youtube for full tutorial of instagram py portable
step by step and making custom wordlist if possible. I'll give you PUBG
gift on steam. I just really need your help man.

**Comment by antony-jr** [comment]
@Teokyun No need for money and I'dont have steam , I will make a youtube video soon!

**Comment by antony-jr** [comment]
@Teokyun  Here is the video on the usage of **Instagram-Py Portable** , https://www.youtube.com/watch?v=nNfSyI_Q9SM
