### ISSUE TITLE
Instagram hack brute force

### ISSUE THREAD

**Issue by DinithEzra** [antony-jr/ama#15]
heyy bro i really need ure help !! i tried the brute force hacking but an error occurred. !! Anyway if ure not busy can u please hack the password of this instagram account for me 
 Account username :  _ judyperera_

the error says the password list couldn't found !! in the "apt-get install python3-setuptools"

im just curious to get the password !!

**Comment by antony-jr** [comment]
@DinithEzra If you use instagram-py **portable version** then you must use **absolute path for password list** (i.e) Wordlist/password.lst (relative path) -> /home/root/Desktop/Wordlist/password.lst (absolute path) , And **I really recommend you to use the portable version , Follow the instructions at the official repo** -> https://github.com/antony-jr/instagram-py , Or if you are a visual learner see this video -> https://www.youtube.com/watch?v=nNfSyI_Q9SM&t=40s on how to use the portable version.

Also Instagram-Py Support is dropped , You can try this simple to use similar tool which uses the instagram-py algorithm where support is still there. https://github.com/thelinuxchoice/instashell , See ya! Have great day. :+1:

**Comment by DinithEzra** [comment]
kk thanks bro ..... i ll try and let u know !!! thank u very much for the info.

**Comment by DinithEzra** [comment]
@antony-jr Bro i used this link https://github.com/thelinuxchoice/instashell and followed up the evry single step ! when i typed "sudo ./install.sh"in the terminal its says "installing Tor please wait" that's it I've waited 2 hrs nothing happed that's all !!

**Comment by antony-jr** [comment]
@DinithEzra Please Report this on the author's issue tracker , https://github.com/thelinuxchoice/instashell/issues , I can't do anything about the errors on his script.

Did you try **'instagram-py portable'** ? Give it a try. (Make sure you are not running any tor server when you run the portable version ).

**Comment by Faiz921** [comment]
Bro when I found the password the terminal close automatically pls fix this issue
