### ISSUE TITLE
Need help with IG access

### ISSUE THREAD

**Issue by magicfoxseh** [antony-jr/ama#21]
Hey Anthony, I am really foreign to this but was recommended to you from a friend. I need help with this on a personal issue - can you send me a link to where i can contact you privately ? 

Hear from you soon! 

Thank you

**Comment by antony-jr** [comment]
I think you can contact me through my email , antonyjr@protonmail.com or at twitter , https://twitter.com/antonyjr0

**Comment by magicfoxseh** [comment]
Thank you - sent you an email
