### ISSUE TITLE
For config invalid or server down

### ISSUE THREAD

**Issue by infinitywxrd** [antony-jr/ama#22]
Hi I’m having the same problem as the last guy but it keeps saying for configuration invalid or server down : : [errno 111] connection refused, I have tried everything you said in the previous post. Please get back to me when you have the time. Thank you!

**Comment by antony-jr** [comment]
@infinitywxrd Try the portable version , https://www.youtube.com/watch?v=nNfSyI_Q9SM0

**Comment by infinitywxrd** [comment]
Thanks
