### ISSUE TITLE
how to ensure vpn and tor proxy working together?

### ISSUE THREAD

**Issue by gingeyy** [antony-jr/ama#26]
Hi,

I was running your instagram-py code and realised that, while my vpn and tor is connected simultaneously, there are still instances that it will not work, and pull out challenge_required when the password is found. Perhaps out of 20tries, only 5 would successfully intercept without the raising the login attempt alert. May I know what is the best way to go about solving this issue? Thank you.

**Comment by antony-jr** [comment]
Unfortunately , Someone have to work on it. I will notify you if I find something useful.
