### ISSUE TITLE
Trouble

### ISSUE THREAD

**Issue by ProxySniper** [antony-jr/ama#29]
Well I thank you for taking your time to make this code and respond to me. This is my first time ever trying to code and I’m having trouble, I got Kali Linux off of the Microsoft store and I applied the exact code in that you did in your screenshots, but when I enter the code it just says could not open lock file or unable to lock the administration. I’m not really sure how to fix this

**Comment by ProxySniper** [comment]
Well I’m trying to use the Instagram-py portable but the link got deleted to it so it won’t work

**Comment by antony-jr** [comment]
@ProxySniper You cannot get Kali linux from Microsoft store.  Try dual booting it , https://www.youtube.com/watch?v=NIRFKLcrF8M , And Also instagram-py will not work anymore that is why its deleted. But if you really want to try it then give this a try -> https://github.com/thelinuxchoice/instashell ( Mostly this won't work too. )

**Comment by ProxySniper** [comment]
Ok, thanks for all the help. I’ll look around for some brute forces that might work
