### ISSUE TITLE
instagram hacking

### ISSUE THREAD

**Issue by zumaricale** [antony-jr/ama#32]
Hello sir,

I am interested in your article from https://null-byte.wonderhowto.com/ entitled "The Only Authentic Way to Hack Instagram!". I would like to speak with you (**privately** if possible) about using the method you describe, but i am really not able to get it done. I am willing to satisfy any **request** you ask me in order for **you** to use the method for me and give me the "result".  Please let me know what you think, also please consider that the account is active.

Regards,
Dani

**Comment by antony-jr** [comment]
@zumaricale I'm not gonna request you anything , Its a dead project , the tool is still available via pip but I highly doubt that it would work as it did before , The reason it fails now is that many people use the same method to attack Instagram and thus the method became invalid. But if you still want to give it a try , then try this [tool](https://github.com/thelinuxchoice/instashell) which uses the exact same method , But I can't make any promises.
