### ISSUE TITLE
Computer dummy 

### ISSUE THREAD

**Issue by Gutlass** [antony-jr/ama#33]
I have zero computer experience and need to do this. Is there anyway of you helping threw the process via email or something? Thanks

**Comment by antony-jr** [comment]
@Gutlass To do what exactly ?

**Comment by Gutlass** [comment]
@Antony-jr Pretty much teach me how to use this program, I don’t have any experience
in terminal or anything like these programs. I’m trying to learn for
ethical reasons and a tutor would be very appreciated in assistance with a
few specific interests.

**Comment by antony-jr** [comment]
@Gutlass The program does not work anymore since many people used the same algorithm , In simple terms we will run out of tor IP's eventually and Instagram will block the attempts again. So we have to find a new way. If you still want to experiment with this then let me know. :+1:

**Comment by Gutlass** [comment]
Can I email your proton address??

**Comment by antony-jr** [comment]
@Gutlass Yes you can. But I kinda reply late when its on email , If you want to get a fast response then post it on github , If its a private message then please do mail me.
