### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by darknitescs** [antony-jr/ama#36]
Hey does this hack actually work and will the person know I hacked their account ?

**Comment by antony-jr** [comment]
@darknitescs Hmm.. the software is discontinued and that means it does not work anymore , you can wait until a new program is created by anyone who is trusted. And if I assume that the program works then , yes the person will not know if his/her account is hacked.
You have to try in one of your fake accounts or your account to actually test if the program works. And as I said before the support for the program is dropped. But there are still a million ways to hack Instagram which is still not explored other than brute force.
