### ISSUE TITLE
Is it possible to see posts through private account without following them?

### ISSUE THREAD

**Issue by rayhanjerome** [antony-jr/ama#38]
Is there any way to do it? If there is, can you please do it for me? Or at least tell us how to do it step by step. Do we need kali linux or whatever OS to do that? I really need to know this cuz im really curious about how this would work haha. Thanks before.

**Comment by antony-jr** [comment]
@rayhanjerome That would be impossible unless you have some kind of access to the target's device or a backdoor in the Instagram's servers(which is improbable). The former case , the target device just have to install a third party app somehow(you could use some social engineering). Or if you are on the extreme side , you could try using a femto cell which I have no experience at all. If you could successfully hack a femto cell , you just have to be in a range of 50m radius of your target , then you could pretty much do anything to the target let alone seeing their Instagram without following them.
