### ISSUE TITLE
Willing to pay!!

### ISSUE THREAD

**Issue by Annedwards** [antony-jr/ama#4]
Hi, I was wondering if it would be possible for you to hack an Instagram account for me and I pay you for your services. I don’t know a thing about hacking but I’m desperate so please help!

**Comment by antony-jr** [comment]
Hey  @Annedwards 

I'm not really a professional pentester. I just build authentic tools and I care more about the code taste. If you see my bio on github , I always wanted to be **Computer Scientist** and if you know computer science , Hacking is a very small part in that. If you want that kind of service , You could just post this **request** on [freelancer](https://www.freelancer.com/) , You can find more **experienced** hackers , I am really **Thankful** for your request but I think I am very **in-experienced**  and can **only** help to use and setup **instagram-py** , You can say I am more of the theory part. But , In case of a  **brute force**(Instagram-Py) attack there is only **50%** chance of cracking the account , there exists a large variety of attacks and that requires more intense social engineering skills. So in conclusion , You can get a **ethical hacker** at **freelancer** with less effort , You can also request them to do a specific work ( Like using brute force attack ).

Thank You for your offer! :heart:

**Comment by briancanspit** [comment]
@Annedwards email me jasmineramona@protonmail.com

**Comment by danielmalto** [comment]
Hi, how do i start installing instagram-py? Is there any kink to download or something? Where do i start? Need help thx

**Comment by antony-jr** [comment]
@danielmalto The project is dead because it stopped working(Therefore you cannot download it but the source is still freely available.) , And @briancanspit please use your email since this is a public channel and so anybody can read it , Just for your safety.

**Comment by tfranzese** [comment]
jasmineramona@protonmail.com is scammer
