### ISSUE TITLE
Hacking

### ISSUE THREAD

**Issue by Nealathon** [antony-jr/ama#40]
Hello Antony, 
I am trying to use your hacking tool, but I am unable to figure out where I'm going wrong. I'm not a hacker by nature, and am kinda lost. Is there anyway I can get in contact with you over text or something so I can have help when I'm doing this?

**Comment by Nealathon** [comment]
If you could text me, my number is 18153558572

**Comment by antony-jr** [comment]
@Nealathon ,please don't post numbers in a public page , see this , https://github.com/antony-jr/ama/issues/4#issuecomment-370117814

**Comment by Nealathon** [comment]
I'm sorry. But is there anyway you can help me? I'm willing to pay and everything

**Comment by Nealathon** [comment]
I’n sorry. Is there anyway you can help me? I’m willing to pay

**Comment by antony-jr** [comment]
@Nealathon sorry , its same as I said in https://github.com/antony-jr/ama/issues/4#issuecomment-370117814
