### ISSUE TITLE
instagram-py

### ISSUE THREAD

**Issue by shubhambishnoi** [antony-jr/ama#41]
getting this error again and again after reinstalling and executing all steps repeatedly can u pls tell me where I am doing it wrong btw I am not using kali I am on ubuntu 16.0

Instagram-Py 2.0.7 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr.

[+] Started @ 2019-09-22 23:42:21.499646
fatal error:: password list not found at /path/to/password_list.txt.

**Comment by antony-jr** [comment]
@shubhambishnoi Hmm... Instagram-Py is not supported and was dropped a long time ago. The support was dropped because I did not want to abuse the TOR project.
