### ISSUE TITLE
instainsane problem

### ISSUE THREAD

**Issue by Knrd2** [antony-jr/ama#45]
Hi, thanks for providing such great work! 
I have a problem with the instainsane project where the command stops with the following message: 
./instainsane.sh: line 575: [: 100: unary operator expected

Do you know how to fix this? Ive tried to adapt the script but wasnt successfull... 

Thanks!

**Comment by antony-jr** [comment]
@Knrd2 why you asking me this, I'm not the maintainer. Please contact https://github.com/thelinuxchoice

IMO that guy is just mysterious, I would personally not use that tool since it won't work for sure, Trust me(Instagram fixed it a year ago). Nothing personal, just my two cents on the issue.
