### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gucciguscrain** [antony-jr/ama#48]
Hey. I need your help. A long time ago, when I was really young, I made an instagram account and eventually forgot about it and made a new one. Now that I'm older, people I know look up my name and see the old account and they make fun of the things I used to post. People really bully me about it. I have tried to remember the password I made but I tried everything and I can't remember. I cant remember any of the re-verification details either. Can you help me find the password? 
The username is: royalcrain
If you don't believe me I can prove this is true. Please help me. 
If you do, I will compensate you.
-gus crain

**Comment by antony-jr** [comment]
@gucciguscrain I really like to help but I think we can't do anything about inactive accounts. We can't trick the system so to speak but only trick people, If no people has the password or the verification medium then your account is simply locked forever.

**However, you can email instagram support directly explaining your situation and they will delete your account directly. I've done this in the past with google to remove my old pictures off the internet.**

**Comment by gucciguscrain** [comment]
Worth a shot i guess, thank you.
