### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by losangelesraiders17** [antony-jr/ama#5]
Hello I’m stuck and don’t know how to enter the username and how to get passwords I’ve done everything else but I don’t know how to enter this last step can you please help I get fatal error password list not found but I’m sure I’m entering all wrong

**Comment by shubhambishnoi** [comment]
you should have a file with common passwords in it which will be used for brute force attack so download a password text file containing common passwords from github and then input the address of downloaded path as the last argument to the command
