### ISSUE TITLE
keeps repeating same pass with varying ip

### ISSUE THREAD

**Issue by ghost** [antony-jr/ama#50]
![IMG_20210718_182037](https://user-images.githubusercontent.com/87435145/126067723-114e6976-ded0-45e9-9978-4e044d6be54f.jpg)
can i make it brute only one time instead of 20-30 check you know pass list contains more than million pass it gonna take ages. ps i love it thanks

**Comment by antony-jr** [comment]
It is keeping trying the same pass because Instagram is blocking all TOR IPs. Sorry I dropped support for this long time ago because brute force is not practical and time consuming. Better try some other method like Man in the middle attack with your evil AP.
