### ISSUE TITLE
📁🤔 I can't get QArchive to work in my project (Qt5.15 on MacOS).

### ISSUE THREAD

**Issue by Alexuds79** [antony-jr/ama#53]
Hello Antony! I'm creating a Qt5 project (using QtCreator on MacOS) in which I'm planning to use your library to compress and decompress files and folders. The problem is that when I try to run your sample codes, it doesn't seem to do anything after invoking `Compressor.start()`. I attach the sample code that I am trying to run:

```cpp
QString ArchivePath = "/path/to/my/Desktop/test.zip";
QStringList Files;
Files.append("/path/to/my/Desktop/example_file.txt");

QArchive::DiskCompressor Compressor(ArchivePath);
Compressor.addFiles(Files);

qDebug() << "[TEST] Compressor created!";

/* Connect Signals with Slots (in this case lambda functions). */
QObject::connect(&Compressor, &QArchive::DiskCompressor::started, [&]() {
    qInfo() << "[+] Starting Compressor... ";
});

QObject::connect(&Compressor, &QArchive::DiskCompressor::finished, [&]() {
    qInfo() << "[+] Compressed File(s) Successfully!";
    return;
});

QObject::connect(&Compressor, &QArchive::DiskCompressor::error, [&](short code, QString file) {
    qInfo() << "[-] An error has occured :: " << QArchive::errorCodeToString(code) << " :: " << file;
    return;
});

QObject::connect(&Compressor, &QArchive::DiskCompressor::progress, [&](QString file, int proc, int total, qint64 br, qint64 bt) {
    if (bt == 0) bt = 1;
        
    qInfo() << "Progress::" << file << ":: Done ( " << proc << " / " << total << ") " << (br * 100/bt)  << "%.";
    return;
});

Compressor.start();
```

I am sure that the paths I am giving are correct and accessible. The output stays at the following and does absolutely nothing else:

```
"[TEST] Compressor created!";
```

Thanks in advance for your support! :)

**Comment by antony-jr** [comment]
What version of QArchive are you using?

**Comment by antony-jr** [comment]
@Alexuds79 Can you try building this example project -> https://github.com/antony-jr/QArchive/tree/master/examples/disk_compressor

or just build QArchive with this and test out the compressor,
```
git clone https://github.com/antony-jr/QArchive
cd QArchive
mkdir build
cd build
cmake -DBUILD_EXAMPLES=ON ..
cd examples/disk_compressor
./DiskCompressor test.zip /path/to/some/file.txt /path/to/some/other/file.txt /and/so/on.txt
```

**Comment by antony-jr** [comment]
See if that compresses those files into the test.zip file.

**Comment by antony-jr** [comment]
Also did you follow the special instructions for MacOS when installing? https://antonyjr.in/QArchive/docs/Installation.html#special-instruction-for-macos

**Comment by Alexuds79** [comment]
Hi! When I try to build that way, I get the following error just after running `cmake -DBUILD_EXAMPLES=ON ..`:

```
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibArchive (missing: LibArchive_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindLibArchive.cmake:64 (find_package_handle_standard_args)
  CMakeLists.txt:46 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/alema/Desktop/test/QArchive/build/CMakeFiles/CMakeOutput.log".
See also "/Users/alema/Desktop/test/QArchive/build/CMakeFiles/CMakeError.log".
```

While setting up the Qt project (with CMake) I got the same error, which is solved by adding the following to the CMakeLists.txt of the project:

```
set(LibArchive_INCLUDE_DIR "/usr/local/opt/libarchive/include")
```


Here is the error as returned by Qt Creator:
```
/Users/alema/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230: error: Could NOT find LibArchive (missing: LibArchive_INCLUDE_DIR) /Users/alema/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE) /Users/alema/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.21/Modules/FindLibArchive.cmake:64 (find_package_handle_standard_args) libs/QArchive/CMakeLists.txt:46 (find_package)
```

**Comment by Alexuds79** [comment]
And yes, I followed the Mac installation steps without any problems :)

**Comment by Alexuds79** [comment]
By making a series of modifications to the `CMakeLists.txt` in the main directory I get from cloning the repository, I was able to run the examples (compressor and decompressor) using the terminal. Both examples work perfectly. So I understand that the installation is correct.

These are the lines I had to add:

```
set(LibArchive_INCLUDE_DIR "/usr/local/opt/libarchive/include")
set(CMAKE_PREFIX_PATH "/usr/local/opt/qt5")
```

Still, I can't get it to work in Qt at the moment. The project builds without much difficulty (just needs to add a couple of lines to the project's `CMakeLists.txt`), but `Compressor.start()` doesn't seem to do anything anyways. Researching a bit in the code without knowing the library in depth, the `start` method is actually invoked, but this method makes a call to `invoke` which seems to be no longer called.

The method involved belongs to the `qarchivecompressor.cc` file (line 130):

```
void Compressor::start() {
    getMethod(*m_Compressor, "start()")
    .invoke(m_Compressor.get(), Qt::QueuedConnection);
}
```

I'm using version 2.2.4, which is the one that I get by adding the library as a submodule (`git submodule add https://github.com/antony-jr/QArchive`). Here is an extract from the `git log`:

```
commit 5c174ed83f78cb7403281fcb6a53db69a452928e (HEAD -> master, tag: v2.2.4, origin/master, origin/HEAD)
Author: antony-jr <antonyjr@protonmail.com>
Date:   Wed Dec 21 21:16:31 2022 +0530

    [Release v2.2.4] QArchive v2.2.4 release.
    
    This release has some minor bug fixes and refactoring,
    move from Qt's Smart Pointers to C++ Standard Smart Pointers
    whenever possible. Optimized IO Reader to reduce bad performance.
    Handle libarchive versions properly when using ZSTD to compress and
    other minor fixes.
```

**Comment by antony-jr** [comment]
@Alexuds79 I'm getting a idea of what you are doing, so you are using Qt Creator... I hope you installed libarchive through homebrew,you can try this without modifying the CMakeLists.txt, you can but it's better if you give ```-D``` to cmake itself.
You just need to give this build option (I think there is a option in Qt Creator).
```
-DLIBARCHIVE_PKG_CONFIG=$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc
```

No need to give any other variables, no need for include dir, just give ```LIBARCHIVE_PKG_CONFIG``` build option as shown
above as mentioned in the docs.

The library actually works on MacOS, even now, I use it in my program -> https://github.com/antony-jr/spirit/blob/17718213ebe100854ce81219be0f594a73817cc0/.github/workflows/deploy.yml#L292

**PS**: I get a lot of issues similar to this with QArchive, mostly because of libarchive, I have perfect solution for this to enable users to easily install the library in Qt Creator, that's gotta need some time.

**Comment by antony-jr** [comment]
@Alexuds79 was this resolved?

**Comment by Alexuds79** [comment]
Unfortunately, no @antony-jr. I have tried several ways to add that parameter to Qt Creator but I get other errors that prevent the project from building.

For example, one way to add it is to add this line to your `CMakeLists.txt`:

```
set(LIBARCHIVE_PKG_CONFIG "/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc")
```

Thus, the beginning of the file would look like this:

```
# Find the QtCore library and libarchive.
# In macOS, if libarchive is installed via homebrew,
# it does not link well with CMake. The only workaround to
# this is to give the absolute path of the libarchive pkg
# config (.pc) file to find the actual libarchive installed
# via brew. If this is not done, cmake always seems to find 
# the libarchive installed in system by default.
# 
# Usage:
# cmake -DLIBARCHIVE_PKG_CONFIG=$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc
# ---

set(LIBARCHIVE_PKG_CONFIG "/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc")

if(APPLE AND LIBARCHIVE_PKG_CONFIG)
   set(PKG_CONFIG_EXECUTABLE pkg-config --define-prefix "${LIBARCHIVE_PKG_CONFIG}")
   find_package(PkgConfig REQUIRED)
   pkg_check_modules(LIBARCHIVE REQUIRED libarchive IMPORTED_TARGET)
   if(NOT LIBARCHIVE_FOUND)
      find_package(LibArchive REQUIRED)
   endif()
else ()
   find_package(LibArchive REQUIRED)
endif()
```

When running `cmake`, the error is as follows:

```
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:411 (message):
  Unknown keywords given to FIND_PACKAGE_HANDLE_STANDARD_ARGS():
  "--define-prefix;/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc"
  --version

      failed with output:

  

      stderr: 
        
      result: 

  No such file or directory"
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  libs/QArchive/CMakeLists.txt:48 (find_package)
```

I have been researching and cannot find much information about this error. Anyway, if I add that variable in the `cmake` configuration of the project, the result is the same.

**Comment by Alexuds79** [comment]
However, I have found that by commenting on the following lines in the `CMakeLists.txt` the project builds successfully, but the result is what I already have: it does nothing.

```
set(PKG_CONFIG_EXECUTABLE pkg-config --define-prefix "${LIBARCHIVE_PKG_CONFIG}")
pkg_check_modules(LIBARCHIVE REQUIRED libarchive IMPORTED_TARGET)
```

**Comment by Alexuds79** [comment]
Also, by modifying this line:

```
set(PKG_CONFIG_EXECUTABLE pkg-config --define-prefix "${LIBARCHIVE_PKG_CONFIG}")
```

For this one:

```
set(PKG_CONFIG_EXECUTABLE "${LIBARCHIVE_PKG_CONFIG}")
```

The error I get is different:

```
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc" --version
      failed with output:

  

      stderr: 
        
      result: 

  Permission denied
```

**Comment by antony-jr** [comment]
Okay, I kind of get why you get this. Try this, instead of adding the project as submodule to your project, install QArchive to your system and use it with ```find_package(QArchive)``` in your project. In your terminal, Install using the following commands, (Do not use Qt Creator, just use your Terminal for Installation only)

```
 brew install qt@5 libarchive pkg-config
 git clone https://github.com/antony-jr/QArchive
 cd QArchive
 mkdir build
 cd build
 export QT_DIR=$(brew --prefix qt@5)
 export Qt5_DIR=$(brew --prefix qt@5)
 cmake -DLIBARCHIVE_PKG_CONFIG=$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc ..
 make -j$(nproc)
 sudo make install]
```
Don't edit anything in the CMakeLists.txt file, get a fresh copy of QArchive from github. After installation, don't add QArchive as subdirectory, just use ```find_package(QArchive)``` in your project and link it on add_executable.

**Comment by Alexuds79** [comment]
I think I get the same error after running in my terminal: `cmake -DLIBARCHIVE_PKG_CONFIG=$(brew --prefix libarchive)/lib/pkgconfig/libarchive.pc ..`

```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:411 (message):
  Unknown keywords given to FIND_PACKAGE_HANDLE_STANDARD_ARGS():
  "--define-prefix;/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc"
  --version

      failed with output:

  

      stderr: 
        
      result: 

  No such file or directory"
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  CMakeLists.txt:40 (find_package)
```

Anyway, I would be interested in having the library working as a submodule, since when the application is distributed, I cannot expect the user to have the library installed on their computer.

**Comment by antony-jr** [comment]
@Alexuds79 Thank you for your time, I think I have a fix for this, but currently can't verify it since **upstream libarchive brew is currently broken.** https://github.com/Homebrew/homebrew-core/issues/117869, let's wait for a while.

**Comment by Alexuds79** [comment]
Of course! Thank you so much for your help. If you need me to do any tests, feel free to let me know. I'll keep an eye on this thread.

**Comment by antony-jr** [comment]
You can try the ```macos-fix``` branch of the repo as the submodule, use it in your project's cmake as this,

```
set(LIBARCHIVE_PKG_CONFIG "/usr/local/opt/libarchive/lib/pkgconfig/" CACHE STRING "Make CMake find LibArchive under MacOS" FORCE)
add_subdirectory(QArchive)

find_package(Qt5 COMPONENTS Core)

SET(source)
list(APPEND source main.cc)

add_executable(MyCoolApplication ${source})

target_link_libraries(MyCoolApplication PUBLIC Qt5::Core QArchive)
```

If you have libarchive@3.6.1 or libarchive@3.6.0 installed via homebrew, then you will compile just fine, the v3.6.2 has bugs in hombrew which will fail the build with ```iconv``` error.

**Comment by Alexuds79** [comment]
I've been doing some research and it seems that it's not easy to revert to the `v3.6.1` via `homebrew` (at least I haven't found a way to do it). I have tried deleting the line:

```
Requires.private: iconv
```

From the file: `/usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc`

And the project builds, but still does nothing after calling: `Compressor.start();`

Is there any way to include `libarchive-3.6.1` as a library in the project, and use it instead of using the one installed via `homebrew (v3.6.2)`?

**Comment by antony-jr** [comment]
Seems odd, everything seems to work just fine with macOS CI/CD with QArchive added as a subdirectory... See example repo at https://github.com/antony-jr/QArchive-MacOS-Subdirectory-Example and see CI/CD output -> https://github.com/antony-jr/QArchive-MacOS-Subdirectory-Example/actions/runs/3832033779/jobs/6521869649

I used the ```macos-fix``` branch of QArchive repo, use it to see everything works. If you confirm it works, I will merge it to master.

**Comment by Alexuds79** [comment]
In my case, the project is built, but when it comes to testing it, it runs but doesn't make anything at all. I don't know why.

- I've reinstalled the libraries: `brew install qt@5 libarchive pkg-config gnu-sed`.
- I've patched the library file: `gsed -i '/Requires.private: iconv/d' /usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc`.
- Then, I've added the submodule and set it to the `macos-fix` branch.

Maybe the problem is related to this warning:

```
ld: warning: dylib (/usr/local/Cellar/libarchive/3.6.2/lib/libarchive.dylib) was built for newer macOS version (13.0) than being linked (10.13)
```

Also, my code looks like this:

```
//Testing compressor
QString file = "/Users/alema/Desktop/file.txt";
QArchive::MemoryCompressor compressor(QArchive::ZipFormat);
compressor.addFiles(file);

QObject::connect(&compressor, &QArchive::MemoryCompressor::error, [&]() {
        qDebug() << "[-][TEST] COMPRESSOR ERROR";
});

QObject::connect(&compressor, &QArchive::MemoryCompressor::finished, [&](QBuffer *archive) {
        qDebug() << "[+][TEST] COMPRESSOR FINISHED";
});

compressor.start();
```

Output: ` ` (and no zip generated).
Expected output: `[+][TEST] COMPRESSOR FINISHED` (and a zip file generated). Or it could even show an error (`[-][TEST] COMPRESSOR ERROR`).

**Comment by antony-jr** [comment]
> ld: warning: dylib (/usr/local/Cellar/libarchive/3.6.2/lib/libarchive.dylib) was built for newer macOS version (13.0) than being linked (10.13)

This is exactly the reason why it fails silently, it's not a QArchive bug per se.. You can use the example repo to build your project on Github Actions just fine. 

**MacOS 10.13 is not supported by homebrew so you can expect broken libraries.** your best bet to install libarchive properly in MacOS 10.13 is to build libarchive from source and install it to your system, then use QArchive. (You can't expect homebrew to work properly)

**Comment by antony-jr** [comment]
@Alexuds79 you can try **Meson** build system, QArchive will build libarchive automatically, all it needs is Qt installed. I'm not very much familiar with Meson but it is an alternative to CMake and some projects supports meson ports and some don't. 

```
brew install meson ninja qt5

cd QArchive
mkdir build

meson setup ./build -Ddefault_library=static -Dqt6=disabled -Dpkg_config_path=/usr/local/opt/qt@5/lib/pkgconfig
meson compile -C ./build --verbose

# Run tests
meson test -C ./build --verbose

# Install to System
meson install -C ./build --verbose
```
