### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by JujuX97** [antony-jr/ama#7]
Hey i'm Julian, My Instagram was hacked and I really need help getting it back. I'm not good at computer stuff I was wondering if you could do it for me, or guide me.

**Comment by antony-jr** [comment]
Sorry and thank you for considering me as a help but unfortunately,I cannot do these kind of service.I recommend you to visit https://freelancer.com or see guides on instagram-py on youtube ( Just search instagram-py ).
