### ISSUE TITLE
Please help me with Instagram-py.

### ISSUE THREAD

**Issue by ghost** [antony-jr/ama#8]
Sir, 
Please help me with your Instagram-py script as when i try to enter this in terminal: [ apt-get install python3-pip ] it says unable to locate package python3-pip.

**Comment by antony-jr** [comment]
Hey @Deathhacker ,
I think you need to upgrade your os , You can do so by the following command.

```
 $ sudo apt-get update 
 $ sudo apt-get upgrade
```

and then follow the installation guide , here is the project page -> https://github.com/antony-jr/instagram-py
