### ISSUE TITLE
Instagram-py

### ISSUE THREAD

**Issue by pranjal123saxena** [antony-jr/ama#9]
Hi Antony,
Everything went smoothly upto the last step, then it says

 fatal error: can't find the password list

Do we have to use anything else in place of  password_list.txt? 
_ can you please help me and rewrite the last line of the programme for me? Please? Also can you please tell me if I want to use some other wordlist document what should I do? Like if you update a new document then what changes should be made in the programme in future?
Thanks in advance.
I really need help. Please reply asap.

**Comment by pranjal123saxena** [comment]
Talking about the Kali Linux here. Thanks again.

**Comment by antony-jr** [comment]
@pranjal123saxena You have to mention the path to a list of passwords , example , If you have a list of passwords in a text file called **rockyou.txt** then you have to replace **password_list.txt** with the path to **rockyou.txt**

``` instagram-py -u targetaccount -pl /path/to/password/list ``` 

There is no need to change any source , you have to mention the path to the wordlist...

**Comment by pranjal123saxena** [comment]
Can you suggest me some good password lists? and by 'you have' means I have to download a word list in .txt format while using live Kali on my PC right??

**Comment by pranjal123saxena** [comment]
And now while restarting the Kali Linux, do I have to do the whole procedure again from the very start?

**Comment by pranjal123saxena** [comment]
Just one more thing..I know I am annoying you but I am a complete moron when it comes to coding! Do we have to save this password list in any specific folder or just downloading it to the PC will do the work?

**Comment by antony-jr** [comment]
@pranjal123saxena You can use any password list from anywhere located in your PC , **rockyou.txt** is a default wordlist present somewhere in **Kali Linux**.. Yes If you live boot then you have to install instagram-py everytime but using presistance will save you that time. One feature of instagram-py is to resume attacks but you must enable presistance for that too...

**Comment by antony-jr** [comment]
@pranjal123saxena You can even do a sniper attack if you want!

**Comment by pranjal123saxena** [comment]
when i enter the command "service tor status" it gets disruptly closed without showing a new line to type what to do now??
![img_20180330_065323027](https://user-images.githubusercontent.com/37745131/38120782-6e285bd6-33ba-11e8-923b-43db68b4b212.jpg)

**Comment by antony-jr** [comment]
CC: @pranjal123saxena 

**Linux Basics:** press **'q'** to quit.

**Comment by pranjal123saxena** [comment]
Tried doing that. It says "Invalid tor configuration or server down [Errno 111] connection refused."

**Comment by pranjal123saxena** [comment]
It's still showing invalid configuration or server down like that first line in the above uploaded image. What to do now?

**Comment by antony-jr** [comment]
@pranjal123saxena This issue is the most asked , Here is a issue where this is solved... https://github.com/antony-jr/instagram-py/issues/3 , Please try the methods I have suggested in the discussion.

**Comment by pranjal123saxena** [comment]
I am not getting how to install this tor browser..nothing else is working and since I am running Kali linux live and logged in as root..it says access denied something..I am totally confused now..I desperately need this..but I am not able to make it work! The to server is not opening any port as the case with that guy..but I didn't understand how he managed to make it work

**Comment by antony-jr** [comment]
@pranjal123saxena I will take your case into consideration as to make the tool more easier to use. Could you wait a day or so till the release ? The resultant will be a single executable which will take care of all tor stuff inside itself , sounds good ?

So Please wait a bit... I'm openning a issue(https://github.com/antony-jr/instagram-py/issues/6) on your behalf. :+1:

**Comment by pranjal123saxena** [comment]
Thank you so much Antony :))

**Comment by antony-jr** [comment]
@pranjal123saxena Here is the ultra portable version , You **don't even need python or tor server installed** (*Run it in live boot of Kali Linux 64 Bits*).

Just execute this command to install instagram-py , You **don't need to configure anything** , Cool right ?
**You can do this in any Linux Distro which is 64 Bit** (*So go wild!*)

```
$ sudo wget -O /usr/bin/instagram-py https://git.io/vxKaq;sudo chmod +x /usr/bin/instagram-py
$ instagram-py # installed
```

Read more about this on the official repo -> https://github.com/antony-jr/instagram-py
if you have any issues please open a issue at the **official repo** ( https://github.com/antony-jr/instagram-py/issues/new ).
Thank You for your Time! :+1:
